dofile(os.getenv('PWD')..'/Core/exploration/costs/basic.lua')
dofile(os.getenv('PWD')..'/Core/exploration/MRE/basic.lua')
dofile(os.getenv('PWD')..'/Core/exploration/SRE/basic.lua')
dofile(os.getenv('PWD')..'/Core/exploration/grid/basic.lua')
dofile(os.getenv('PWD')..'/Core/exploration/assign.lua')
